T5
owsym/barq_weather_task pull request #3
Opened 2023-03-20 07:38 UTC by owsym

2023-03-20 08:37 UTC, Hamma111 requested changes

2023-03-20 08:37 UTC, Hamma111 commented on task/t5.py
> +    if event == "Rain" or event == "Snow" or event == "Rain-Snow":
better way":
```
if events in ["Rain", "Snow", "Rain-Snow"]:

2023-03-20 08:37 UTC, Hamma111 commented on utils/reader.py
> +def file_content_t5():
use one function to read both files

2023-03-20 08:37 UTC, Hamma111 commented on task/t5.py
> +    event = file_value[22]
[-2] might be easier to read

2023-03-20 08:47 UTC, owsym commented on task/t5.py
> +    if event == "Rain" or event == "Snow" or event == "Rain-Snow":
o k.

2023-03-20 08:48 UTC, owsym commented on task/t5.py
> +    event = file_value[22]
o k.

2023-03-20 08:48 UTC, owsym commented on utils/reader.py
> +def file_content_t5():
ok ill try

2023-03-21 06:38 UTC, Hamma111 requested changes

2023-03-21 06:38 UTC, Hamma111 commented on utils/reader.py
> +def read_files(file_path1, file_path2):
have your function which takes on paramater of file_path and return the files contents from that function. should be used like this
```python
file1_content = read_file(".../f1.csv")
file2_content = read_file(".../f2.csv")

2023-03-21 06:38 UTC, Hamma111 commented on task/vim-demo.txt
didnt you delete these files in the last PR you merged? why are they still here?

2023-03-21 06:43 UTC, Hamma111 commented on task/t5.py
> +    if events in ["Rain", "Snow", "Rain-Snow"]:
good. but study `if x in y`
https://realpython.com/python-conditional-statements/#:~:text=%3E%3E%3E%20if%20%27aul%27%20in%20%27grault%27%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20Truthy

2023-03-21 06:59 UTC, owsym commented on utils/reader.py
> +def read_files(file_path1, file_path2):
ok

2023-03-21 07:04 UTC, owsym commented on task/vim-demo.txt
i did it but idont know to came about

2023-03-21 07:04 UTC, owsym commented on task/t5.py
> +    if events in ["Rain", "Snow", "Rain-Snow"]:
ok

2023-03-21 07:21 UTC, owsym commented on utils/reader.py
> +def read_files(file_path1, file_path2):
could you please explain a little bit about how you want it?

2023-03-21 07:22 UTC, Hamma111 commented on utils/reader.py
> +def read_files(file_path1, file_path2):
one function to read files based on the file path

2023-03-21 11:08 UTC, Hamma111 requested changes

2023-03-21 11:08 UTC, Hamma111 commented on task/t1.py
> +files_directory =file_content("/home/owsym/Project/Python/barq_weather_task/files/f1.csv")
still not relevant name. directory is folder. we dont have a dir or folder, we have the content of values Usama!!

2023-03-21 11:11 UTC, owsym commented on task/t1.py
> +files_directory =file_content("/home/owsym/Project/Python/barq_weather_task/files/f1.csv")
ok "file_values_content"? is correct?

2023-03-21 11:25 UTC, Hamma111 commented on task/t1.py
> +files_directory =file_content("/home/owsym/Project/Python/barq_weather_task/files/f1.csv")
file_values or file_contents would be best

2023-03-21 11:46 UTC, Hamma111 requested changes

2023-03-21 11:46 UTC, Hamma111 commented on utils/reader.py
> +def file_content(files_directory):
rename this function, `get_file_content`

2023-03-21 11:46 UTC, Hamma111 commented on task/t1.py
> +files_directory =file_content("/home/owsym/Project/Python/barq_weather_task/files/f1.csv")
file_contents = ..

2023-03-21 11:59 UTC, owsym commented on task/t1.py
> +files_directory =file_content("/home/owsym/Project/Python/barq_weather_task/files/f1.csv")
ok

2023-03-21 11:59 UTC, merged